language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install  # install catplot
# command to run tests
script:
  - cd scripts/mplot
  - python plot_merge_profile.py --save
  - cd ../plot
  - python plot_energy_profile.py --save